const dotenv = require("dotenv");
const connectDB = require("./config/db");
const Product = require("./models/Product");

dotenv.config();

const products = [
  {
    _id: "p1",
    name: "Sri Ganesha Tanjore Painting",
    category: "Tanjore Paintings",
    description:
      "Gold-foil Tanjore artwork of Lord Ganesha with vivid detailing.",
    price: 4999,
    originalPrice: 6499,
    discount: 23,
    rating: 4.8,
    reviewCount: 124,
    stock: "in-stock",
    badge: "Bestseller",
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P1",
    stockCount: 12,
    material:
      "Wood panel with 22-carat gold foil, gesso relief work and natural stones",
    style: "Traditional Tanjore art",
    dimensions: "10 x 12 inches",
    frame: "Teak wood frame",
    handmade: true,
    customizable: false,
  },

  {
    _id: "p2",
    name: "Krishna Tanjore Artwork",
    category: "Tanjore Paintings",
    description:
      "Traditional Krishna painting finished with 22-carat gold foil.",
    price: 5499,
    originalPrice: 6999,
    discount: 21,
    rating: 4.9,
    reviewCount: 98,
    stock: "in-stock",
    badge: "Bestseller",
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P2",
    stockCount: 12,
    material:
      "Wood panel with 22-carat gold foil, gesso relief work and natural stones",
    style: "Traditional Tanjore art",
    dimensions: "12 x 16 inches",
    frame: "Teak wood frame",
    handmade: true,
    customizable: false,
  },

  {
    _id: "p3",
    name: "Peacock Tanjore Painting",
    category: "Tanjore Paintings",
    description:
      "Ornamental peacock design with rich color and gold work.",
    price: 4599,
    originalPrice: null,
    discount: 0,
    rating: 4.6,
    reviewCount: 41,
    stock: "in-stock",
    badge: "New",
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    image: "",
    images: [],
    sku: "BAW-P3",
    stockCount: 12,
    material:
      "Wood panel with 22-carat gold foil, gesso relief work and natural stones",
    style: "Traditional Tanjore art",
    dimensions: "10 x 12 inches",
    frame: "Teak wood frame",
    handmade: true,
    customizable: false,
  },

  {
    _id: "p4",
    name: "Lakshmi Tanjore Painting",
    category: "Tanjore Paintings",
    description:
      "Goddess Lakshmi rendered in classic Tanjore gold-leaf style.",
    price: 5299,
    originalPrice: 6299,
    discount: 16,
    rating: 4.9,
    reviewCount: 140,
    stock: "in-stock",
    badge: "Bestseller",
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P4",
    stockCount: 12,
    material:
      "Wood panel with 22-carat gold foil, gesso relief work and natural stones",
    style: "Traditional Tanjore art",
    dimensions: "12 x 16 inches",
    frame: "Teak wood frame",
    handmade: true,
    customizable: false,
  },

  {
    _id: "p5",
    name: "Traditional Floral Artwork",
    category: "Fabric Paintings",
    description: "Hand-painted floral motifs on fine fabric.",
    price: 2899,
    originalPrice: 3399,
    discount: 15,
    rating: 4.5,
    reviewCount: 36,
    stock: "in-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    image: "",
    images: [],
    sku: "BAW-P5",
    stockCount: 12,
    material: "Fabric paint on premium cotton fabric",
    style: "Hand-painted fabric art",
    dimensions: "10 x 12 inches",
    frame: null,
    handmade: true,
    customizable: false,
  },

  {
    _id: "p6",
    name: "Customized Couple Portrait",
    category: "Customized Art",
    description: "A personalized hand-painted portrait made to order.",
    price: 7999,
    originalPrice: null,
    discount: 0,
    rating: 5.0,
    reviewCount: 32,
    stock: "low-stock",
    badge: "Made to Order",
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    image: "",
    images: [],
    sku: "BAW-P6",
    stockCount: 2,
    material: "Premium canvas and fabric paint",
    style: "Custom hand-painted artwork",
    dimensions: "Made to order (size discussed at order)",
    frame: "Optional framing available",
    handmade: true,
    customizable: true,
  },

  {
    _id: "p7",
    name: "Fabric Peacock Art",
    category: "Fabric Paintings",
    description: "Hand-painted peacock design on premium fabric.",
    price: 2599,
    originalPrice: 2999,
    discount: 13,
    rating: 4.4,
    reviewCount: 22,
    stock: "in-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    image: "",
    images: [],
    sku: "BAW-P7",
    stockCount: 12,
    material: "Fabric paint on premium cotton fabric",
    style: "Hand-painted fabric art",
    dimensions: "10 x 12 inches",
    frame: null,
    handmade: true,
    customizable: false,
  },

  {
    _id: "p8",
    name: "Hand Painted Blouse Design",
    category: "Blouse Painting",
    description:
      "Custom hand-painted blouse art tailored to your outfit.",
    price: 1999,
    originalPrice: 2499,
    discount: 20,
    rating: 4.7,
    reviewCount: 58,
    stock: "in-stock",
    badge: "Popular",
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P8",
    stockCount: 12,
    material: "Fabric paint on blouse fabric",
    style: "Hand-painted blouse art",
    dimensions: "Made to fit blouse piece (customizable)",
    frame: null,
    handmade: true,
    customizable: true,
  },

  {
    _id: "p9",
    name: "Saraswati Devi Gold Foil",
    category: "Tanjore Paintings",
    description:
      "Goddess Saraswati in traditional gold-leaf Tanjore style.",
    price: 5999,
    originalPrice: 7499,
    discount: 20,
    rating: 4.9,
    reviewCount: 156,
    stock: "in-stock",
    badge: "Bestseller",
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P9",
    stockCount: 12,
    material:
      "Wood panel with 22-carat gold foil, gesso relief work and natural stones",
    style: "Traditional Tanjore art",
    dimensions: "12 x 16 inches",
    frame: "Teak wood frame",
    handmade: true,
    customizable: false,
  },

  {
    _id: "p10",
    name: "Radha Krishna Duet Painting",
    category: "Tanjore Paintings",
    description:
      "A richly detailed depiction of Radha and Krishna together.",
    price: 8499,
    originalPrice: 9999,
    discount: 15,
    rating: 4.8,
    reviewCount: 67,
    stock: "in-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P10",
    stockCount: 12,
    material:
      "Wood panel with 22-carat gold foil, gesso relief work and natural stones",
    style: "Traditional Tanjore art",
    dimensions: "12 x 16 inches",
    frame: "Teak wood frame",
    handmade: true,
    customizable: false,
  },

  {
    _id: "p11",
    name: "Miniature Ganesha Panel",
    category: "Tanjore Paintings",
    description:
      "Compact Tanjore panel, perfect for smaller wall spaces.",
    price: 1899,
    originalPrice: null,
    discount: 0,
    rating: 4.3,
    reviewCount: 19,
    stock: "in-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P11",
    stockCount: 12,
    material:
      "Wood panel with 22-carat gold foil, gesso relief work and natural stones",
    style: "Traditional Tanjore art",
    dimensions: "6 x 8 inches",
    frame: "Teak wood frame",
    handmade: true,
    customizable: false,
  },

  {
    _id: "p12",
    name: "Grand Durga Tanjore Artwork",
    category: "Tanjore Paintings",
    description:
      "Large-format Durga painting with extensive gold detailing.",
    price: 21999,
    originalPrice: 24999,
    discount: 12,
    rating: 5.0,
    reviewCount: 12,
    stock: "in-stock",
    badge: "Premium",
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P12",
    stockCount: 12,
    material:
      "Wood panel with 22-carat gold foil, gesso relief work and natural stones",
    style: "Traditional Tanjore art",
    dimensions: "24 x 36 inches",
    frame: "Teak wood frame",
    handmade: true,
    customizable: false,
  },

  {
    _id: "p13",
    name: "Elephant Motif Fabric Art",
    category: "Fabric Paintings",
    description:
      "Hand-painted elephant motif on soft cotton fabric.",
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    rating: 4.2,
    reviewCount: 14,
    stock: "in-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P13",
    stockCount: 12,
    material: "Fabric paint on premium cotton fabric",
    style: "Hand-painted fabric art",
    dimensions: "6 x 8 inches",
    frame: null,
    handmade: true,
    customizable: false,
  },

  {
    _id: "p14",
    name: "Mandala Fabric Wall Hanging",
    category: "Fabric Paintings",
    description:
      "Hand-painted mandala design on fabric, ready to hang.",
    price: 3299,
    originalPrice: null,
    discount: 0,
    rating: 4.6,
    reviewCount: 27,
    stock: "out-of-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P14",
    stockCount: 0,
    material: "Fabric paint on premium cotton fabric",
    style: "Hand-painted fabric art",
    dimensions: "10 x 12 inches",
    frame: null,
    handmade: true,
    customizable: false,
  },

  {
    _id: "p15",
    name: "Floral Vine Blouse Design",
    category: "Blouse Painting",
    description:
      "Delicate hand-painted floral vine pattern for blouses.",
    price: 1599,
    originalPrice: 1999,
    discount: 20,
    rating: 4.5,
    reviewCount: 33,
    stock: "in-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P15",
    stockCount: 12,
    material: "Fabric paint on blouse fabric",
    style: "Hand-painted blouse art",
    dimensions: "Made to fit blouse piece (customizable)",
    frame: null,
    handmade: true,
    customizable: true,
  },

  {
    _id: "p16",
    name: "Peacock Motif Blouse Art",
    category: "Blouse Painting",
    description:
      "Bold peacock design hand-painted on a blouse piece.",
    price: 2299,
    originalPrice: 2799,
    discount: 18,
    rating: 4.7,
    reviewCount: 45,
    stock: "in-stock",
    badge: "Popular",
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    image: "",
    images: [],
    sku: "BAW-P16",
    stockCount: 12,
    material: "Fabric paint on blouse fabric",
    style: "Hand-painted blouse art",
    dimensions: "Made to fit blouse piece (customizable)",
    frame: null,
    handmade: true,
    customizable: true,
  },

  {
    _id: "p17",
    name: "Temple Border Saree Painting",
    category: "Saree Border Painting",
    description:
      "Traditional temple-inspired border design hand-painted on a saree.",
    price: 3999,
    originalPrice: 4799,
    discount: 17,
    rating: 4.8,
    reviewCount: 51,
    stock: "in-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P17",
    stockCount: 12,
    material: "Fabric paint on saree border fabric",
    style: "Hand-painted saree border art",
    dimensions: "Standard saree border length",
    frame: null,
    handmade: true,
    customizable: false,
  },

  {
    _id: "p18",
    name: "Floral Kalamkari Saree Border",
    category: "Saree Border Painting",
    description:
      "Kalamkari-inspired floral border, hand-painted with fine detail.",
    price: 4499,
    originalPrice: null,
    discount: 0,
    rating: 4.6,
    reviewCount: 29,
    stock: "in-stock",
    badge: "New",
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    image: "",
    images: [],
    sku: "BAW-P18",
    stockCount: 12,
    material: "Fabric paint on saree border fabric",
    style: "Hand-painted saree border art",
    dimensions: "Standard saree border length",
    frame: null,
    handmade: true,
    customizable: false,
  },

  {
    _id: "p19",
    name: "Custom Family Portrait",
    category: "Customized Art",
    description:
      "A personalized hand-painted portrait of your family, made to order.",
    price: 12999,
    originalPrice: 14999,
    discount: 13,
    rating: 4.9,
    reviewCount: 21,
    stock: "in-stock",
    badge: "Made to Order",
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P19",
    stockCount: 12,
    material: "Premium canvas and fabric paint",
    style: "Custom hand-painted artwork",
    dimensions: "Made to order (size discussed at order)",
    frame: "Optional framing available",
    handmade: true,
    customizable: true,
  },

  {
    _id: "p20",
    name: "Customized Pet Portrait",
    category: "Customized Art",
    description:
      "A hand-painted portrait of your pet, made from your photo.",
    price: 3499,
    originalPrice: null,
    discount: 0,
    rating: 4.7,
    reviewCount: 18,
    stock: "in-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: true,
    image: "",
    images: [],
    sku: "BAW-P20",
    stockCount: 12,
    material: "Premium canvas and fabric paint",
    style: "Custom hand-painted artwork",
    dimensions: "Made to order (size discussed at order)",
    frame: "Optional framing available",
    handmade: true,
    customizable: true,
  },

  {
    _id: "p21",
    name: "Festive Gift Hamper – Deluxe",
    category: "Gifts & Crafts",
    description:
      "A curated hamper of handmade art pieces for gifting.",
    price: 2999,
    originalPrice: 3499,
    discount: 14,
    rating: 4.5,
    reviewCount: 62,
    stock: "in-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P21",
    stockCount: 12,
    material: "Assorted handmade materials",
    style: "Handmade gift craft",
    dimensions: "Varies by item in the set",
    frame: null,
    handmade: true,
    customizable: false,
  },

  {
    _id: "p22",
    name: "Handmade Gift Set – Petite",
    category: "Gifts & Crafts",
    description:
      "A smaller handmade gift set, ideal for everyday occasions.",
    price: 999,
    originalPrice: 1299,
    discount: 23,
    rating: 4.3,
    reviewCount: 40,
    stock: "in-stock",
    badge: "",
    isFeatured: false,
    isBestSeller: false,
    isNew: false,
    image: "",
    images: [],
    sku: "BAW-P22",
    stockCount: 12,
    material: "Assorted handmade materials",
    style: "Handmade gift craft",
    dimensions: "Varies by item in the set",
    frame: null,
    handmade: true,
    customizable: false,
  },
];

const seedProducts = async () => {
  try {
    await connectDB();

    await Product.deleteMany({});

    await Product.insertMany(products);

    console.log(`${products.length} products inserted successfully.`);

    process.exit(0);
  } catch (error) {
    console.error("Product seeding failed:", error.message);
    process.exit(1);
  }
};

seedProducts();
